### ISSUE TITLE
add options

### ISSUE THREAD

**Issue by kelerliao** [sindresorhus/gulp-strip-debug#8] opened 2015-05-28 13:18 UTC
### add options
---

#### example

```
stripDebug({debugger: true, console: true, alert: false});
// so:
// del Debugger
// del console
// alert reservation
```

#### code

```
// gulp-strip-debug/index.js
'use strict';
var gutil = require('gulp-util');
var through = require('through2');
var stripDebug = require('strip-debug');

module.exports = function (options) {
	return through.obj(function (file, enc, cb) {
		if (file.isNull()) {
			cb(null, file);
			return;
		}

		if (file.isStream()) {
			cb(new gutil.PluginError('gulp-strip-debug', 'Streaming not supported'));
			return;
		}

		try {
			file.contents = new Buffer(stripDebug(file.contents.toString(), options).toString());
			this.push(file);
		} catch (err) {
			this.emit('error', new gutil.PluginError('gulp-strip-debug', err, {fileName: file.path}));
		}

		cb();
	});
};

// gulp-strip-debug/node_modules/strip-debug/index.js
'use strict';
var rocambole = require('rocambole');
var stripDebugger = require('rocambole-strip-debugger');
var stripConsole = require('rocambole-strip-console');
var stripAlert = require('rocambole-strip-alert');

// esprima@2.1 introduces a "handler" property on TryStatement, so we would
// loop the same node twice (see jquery/esprima/issues/1031 and #264)
rocambole.BYPASS_RECURSION.handler = true;

module.exports = function (src, options) {
    options = options || {};

	return rocambole.moonwalk(src, function (node) {
        options.debugger !== false && stripDebugger(node);
        options.console !== false && stripConsole(node);
		options.alert !== false && stripAlert(node);
	});
};
```

**Comment by sindresorhus** [comment] 2015-05-28 13:51
No thanks.

Duplicate of #5.

**Closed by sindresorhus** 2015-05-28 13:51 UTC
