### ISSUE TITLE
Keep alerts but remove console logs

### ISSUE THREAD

**Issue by njv** [sindresorhus/gulp-strip-debug#13] opened 2016-03-15 16:19 UTC
Is there an easy way to get this plugin to keep alerts while removing the console logs? Would you consider adding this as an option? Thanks

**Comment by sindresorhus** [comment] 2016-03-15 17:01
Duplicate of https://github.com/sindresorhus/gulp-strip-debug/issues/12#issuecomment-165699955.

**Closed by sindresorhus** 2016-03-15 17:01 UTC
