### ISSUE TITLE
Configuration is to block the “alert”

### ISSUE THREAD

**Issue by plokmju88** [sindresorhus/gulp-strip-debug#17] opened 2016-08-30 04:28 UTC
I find will be automatically blocked off the console.log and alert (), is there a way to configure, shielding the console. Only the log (), because in some cases, I am a need to alert () method is executed

**Comment by sindresorhus** [comment] 2016-08-30 10:01
Duplicate of https://github.com/sindresorhus/gulp-strip-debug/issues/16.

**Closed by sindresorhus** 2016-08-30 10:01 UTC
